### ISSUE TITLE
ParameterNotFoundException: hackzilla_ticket.user_bridge.clas

### ISSUE THREAD

**Issue by Assada** [hackzilla/TicketBundle#33]
Jast after instalation bundle:
```
ParameterNotFoundException: The service "hackzilla_ticket.user" has a dependency on a non-existent parameter "hackzilla_ticket.user_bridge.class". Did you mean one of these: "hackzilla_ticket.user_load.class", "hackzilla_ticket.twig_user.class", "hackzilla_ticket.ticket_manager.class"?
```

*vendor/hackzilla/ticket-bundle/Resources/config/services.yml*
```
....
hackzilla_ticket.user:
        class: %hackzilla_ticket.user_bridge.class%
        arguments: ['@service_container']
....
```

but parameters(in this services.yml):
```
parameters:
    hackzilla_ticket.user_load.class: Hackzilla\Bundle\TicketBundle\EventListener\UserLoad
    hackzilla_ticket.twig_user.class: Hackzilla\Bundle\TicketBundle\Extension\UserExtension
    hackzilla_ticket.ticket_manager.class: Hackzilla\Bundle\TicketBundle\Manager\TicketManager

services:
....
```
where is *%hackzilla_ticket.user_bridge.class%* param?

after this dedective i`m install yours [FOSUserBridge](https://github.com/hackzilla/FOSUserBridge) 
```
composer require hackzilla/fosuser-bridge-bundle
```

and add param in *vendor/hackzilla/ticket-bundle/Resources/config/services.yml*
```
hackzilla_ticket.user_bridge.class: Hackzilla\Bundle\FOSUserBridgeBundle\User\FOSUser
```

and all works fine!
![Image of Yaktocat](http://i.imgur.com/JNKLvSG.png)
