### ISSUE TITLE
Override form

### ISSUE THREAD

**Issue by Filoz** [hackzilla/TicketBundle#65]
While I try your fantastic bundle  I always think new features;
something that can be very usefull is the ability to override forms, exactly like Model entities (with a setting) https://github.com/hackzilla/TicketBundle/blob/develop/DependencyInjection/Configuration.php#L24 ;

This can be very useful, let's think at this example:
E-commerce:
you to add a ticket for a recent purchase; you can select it from a drop down directly when you add the ticket.

If you want I can write the needed code

**Comment by hackzilla** [comment]
Sounds good.

Thanks, yeah I would appreciate it if you would.

**Comment by bubnovKelnik** [comment]
+1. Now we may easily override forms by custom compiler
http://symfony.com/doc/current/bundles/override.html

It whould be great to extend CustomTicketMessageType from original TicketMessageType.
But all TicketMessageType`s vars are private :(

**Comment by hackzilla** [comment]
I can getters for the private variables if that would help? or I could make them protected.

**Comment by hackzilla** [comment]
I was expecting people could override by using

```
    hackzilla_ticket.form.type.ticket_message:
        class: ..\CustomTicketMessageType
        arguments:
            - '@hackzilla_ticket.user_manager'
            - '@hackzilla_ticket.features'
            - '%hackzilla_ticket.model.message.class%'
        tags:
            - { name: form.type, alias: hackzilla_ticket_message }
```
services.yml

Which it makes sense you want access to TicketMessageType's privates
